const info = [
  {
    id: 1,
    title: "Lower Cost Solar Panel in America",
    desc: 'Money Back Guarantee',
    backgroundImage: require('../assets/Desktop-Accessories.jpg'),
    leftBtnText: 'Order Now',
    leftBtnLinks: '',
    rightBtnText: 'Learn More',
    rightBtnLinks: '',
    twoButtons: true,
    first: true,
  },
  {
    id: 2,
    title: "Tesla Model S",
    desc: '$69,428',
    backgroundImage: require('../assets/Desktop-Model3.jpeg'),
    leftBtnText: 'Custom Order',
    leftBtnLinks: '',
    rightBtnText: 'LEARN MORE',
    rightBtnLinks: '',
    twoButtons: true,
  },
  {
    id: 3,
    title: "TModel 3",
    desc: '$69,428',
    backgroundImage: require('../assets/Desktop-ModelS.jpeg'),
    leftBtnText: 'Custom Order',
    leftBtnLinks: '',
    rightBtnText: 'LEARN MORE',
    rightBtnLinks: '',
    twoButtons: true,
  },
  {
    id: 4,
    title: "Lower Cost Solar Panel in America",
    desc: 'Money Back Guarantee',
    backgroundImage: require('../assets/Desktop-ModelX.jpeg'),
    leftBtnText: 'Order Now',
    leftBtnLinks: '',
    rightBtnText: 'Learn More',
    rightBtnLinks: '',
    twoButtons: true,

  },
  {
    id: 5,
    title: "Tesla Model S",
    desc: '$69,428',
    backgroundImage: require('../assets/Desktop-ModelY.jpeg'),
    leftBtnText: 'Custom Order',
    leftBtnLinks: '',
    rightBtnText: 'LEARN MORE',
    rightBtnLinks: '',
    twoButtons: true,
  },
  {
    id: 6,
    title: "TModel 3",
    desc: '$69,428',
    backgroundImage: require('../assets/Desktop-SolarPanels.jpeg'),
    leftBtnText: 'Custom Order',
    leftBtnLinks: '',
    rightBtnText: 'LEARN MORE',
    rightBtnLinks: '',
    twoButtons: true,
  },
];

export default info;
